<?xml version="1.0" encoding="utf-8"?>
<Database Name="ExemploBruno" Class="LojaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LC-PC\SQLEXPRESS;Initial Catalog=ExemploBruno;Integrated Security=True" SettingsObjectName="Loja.DAL.Properties.Settings" SettingsPropertyName="ExemploBrunoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_categoria" Member="Categorias">
    <Type Name="Categoria">
      <Column Name="id_categoria" Member="Codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="descricao_categoria" Member="Descricao" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="tb_categoria_tb_produto" Member="Produtos" ThisKey="Codigo" OtherKey="CodigoCategoria" Type="Produto" />
    </Type>
  </Table>
  <Table Name="dbo.tb_produto" Member="Produtos">
    <Type Name="Produto">
      <Column Name="id_produto" Member="Codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ds_produto" Member="Descricao" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="vl_preco" Member="Preco" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="id_categoria" Member="CodigoCategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_categoria_tb_produto" Member="Categoria" ThisKey="CodigoCategoria" OtherKey="Codigo" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
</Database>